### ISSUE TITLE
Stronger filter for files

### ISSUE THREAD

**Issue by Vadorequest** [sgress454/sails-hook-autoreload#30]
In the `config.autoreload`, it would be great to have more options, like filters.

``` js
module.exports.autoreload = {

  active: true,
  usePolling: false,
  dirs: [
    "api/models",
    "api/controllers/**/*.js",
    "api/services",
    "shared/app",
    "!shared/app/public",
    "shared/config"
  ]

};
```

For instance, I'm using TypeScript, and the app restart when I change a .ts file, I don't want that.

So, I think this great plugin needs a better filter. :)

**Comment by sgress454** [comment]
I think it already supports globs, because [Chokidar supports globs](https://github.com/paulmillr/chokidar#api).  Probably could use the [ignored](https://github.com/paulmillr/chokidar#path-filtering) setting to ignore folders in a separate `ignore` array, too.  If you try it out and make a PR, I'll merge it in.
