### ISSUE TITLE
Potential Conflict with sails-hook-babel

### ISSUE THREAD

**Issue by justinanastos** [sgress454/sails-hook-autoreload#36]
This issue is more of a question than issue. 

I am trying to use [sails-hook-babel](https://www.npmjs.com/package/sails-hook-babel) and sails-hook-autoreload. 

The autoreload feature works as expected, refreshing whenever the controllers and/or models change. Unfortunately, after a refresh, I have to save one more time and have it reload again before the changes are picked up. I don't even know where to start regarding debugging this. Could you please lend me a hand?

**Comment by sgress454** [comment]
Thanks for posting @justinanastos.  I'm sort of surprised this works at all, since `sails-hook-babel` only claims to work on lift, and `sails-hook-autoreload` doesn't reload other hooks.  I'm afraid without spending significant time on it, I wouldn't have much of an idea of where to start either.  You might be better of in this case using something like `forever -w` to stop/start Sails on changes.
