### ISSUE TITLE
If have many models and much data will didn't work?

### ISSUE THREAD

**Issue by lvsenlin** [sgress454/sails-hook-autoreload#42]
My project hava many models(15-20) and much data(1000+),wait for a very long time,bu it's not work.
If drop models only leave one or empty database,it's ok.
Why?

**Comment by sgress454** [comment]
This hook defaults to using `migrate: alter`, which is going to take awhile since it drops/recreates your databases and data every time.  The newly published version has an `overrideMigrateSetting` config option that you can set to `false`, and then you can set your app's `migrate` setting in (config/models.js) to `safe` which will speed things way up.  The downside is that changes to model files won't be auto-loaded into your app.

**Comment by lvsenlin** [comment]
thank you
