### ISSUE TITLE
forces migration alter mode

### ISSUE THREAD

**Issue by marcopeg** [sgress454/sails-hook-autoreload#46]
I noticed that this hook enforces a `migration:alter` configuration which conflicts if you are playing with db migrations in dev environment.

I suggest to keep the configuration value that the developer defines in the `config/models.js`config file.

for the rest, great job!

**Comment by risenhoover** [comment]
Unfortunately, this behavior cost us two days of headache when our production database got wiped out from a failed attempt to migrate the schema.

**Comment by sgress454** [comment]
@marcopeg Thanks for posting.  I just published v0.13.0 which has the `overrideMigrateSetting` config option, which you can set to `false` to use your app's migrate setting instead of having the hook override it.  The default is `true` to keep backwards-compatibility, so you'll want to set it to `false` in your apps.

@risenhoover Sorry to hear about your production data!  I should have made it clearer that this module is purely for development purposes, and should not be deployed in any sort of production environment. I've added some notes to the top of the README to that effect.
