### ISSUE TITLE
overrideMigrateSetting should not default to true

### ISSUE THREAD

**Issue by jmo-001** [sgress454/sails-hook-autoreload#59]
The default value for this is very presumptuous. It caused major issues in a project I was working on recently.

**Comment by sgress454** [comment]
I'm sorry to hear that the plugin caused major issues!  I would argue that the biggest presumption that's being made is that folks would [read the usage instructions](https://github.com/sgress454/sails-hook-autoreload#usage), and that they wouldn't be using this in a production environment.  I'm not being sarcastic; I should know better.  I would _not_ presume that you should know about all of the early issues  from users who were annoyed / bewildered that their data either kept disappearing (with `migrate: drop`) or not updating (with `migrate: safe`), which is what led here.  Personally I have no skin in the game since I mostly use this while developing against the disk adapter, which just works out of the box with `migrate: alter`.  If you want to submit a PR that changes this to `false`, and logs a clear warning if the `migrate` setting is anything besides `alter`, I'd be happy to take a look.
